NazeeranHospitalManagement/Models/BloodCP.cs
using NazeeranHospitalManagement.ViewModels.Enums;
using System.ComponentModel.DataAnnotations.Schema;

namespace NazeeranHospitalManagement.Models
{
    public partial class BloodCP
    {
        public int Id { get; set; }
        public double Glucose2HRSABF { get; set; }
        public MedicalTestStatus Status { get; set; }

        [ForeignKey("Prescription")]
        public int PrescriptionId { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}

NazeeranHospitalManagement/Models/CrossMatch.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NazeeranHospitalManagement.Models
{
    public partial class CrossMatch
    {
        public int Id { get; set; }

        [Display(Name = "MRN Of Donor")]
        public int MRNOfDonor { get; set; }

        [Display(Name = "Name Of Donor")]
        public string NameOfDonor { get; set; }

        [Display(Name = "Age Of Donor")]
        public int AgeOfDonor { get; set; }

        [Display(Name = "Relation Of Donor With Patient")]
        public string RelationOfDonorWithPatient { get; set; }

        [Display(Name = "BloodB ag NO")]
        public string BloodBagNO { get; set; }

        [Display(Name = "Patient Blood Group")]
        public string PatientBloodGroup { get; set; }

        [Display(Name = "Cross Match Value ")]
        public string CrossMatchValue { get; set; }

        [ForeignKey("Prescription")]
        public int PrescriptionId { get; set; }

        public virtual Prescription Prescription { get; set; }
    }
}

NazeeranHospitalManagement/Models/TFT.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace NazeeranHospitalManagement.Models
{
    public partial class TFT
    {
        public int Id { get; set; }
        public double TotalT3 { get; set; }
        public string TotalT3Unit { get; set; }
        public double TotalT4 { get; set; }
        public string TotalT4Unit { get; set; }
        public double TSH { get; set; }
        public string TSHUnit { get; set; }


        [ForeignKey("Prescription")]
        public int PrescriptionId { get; set; }

        public virtual Prescription Prescription { get; set; }
    }
}

NazeeranHospitalManagement/ViewModels/LabViewModel.cs
using NazeeranHospitalManagement.ViewModels.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NazeeranHospitalManagement.ViewModels
{
    public class ViewLabTestsViewModel
    {
        public int PatientId { set; get; }
        public string PatientName { set; get; }
        public DateTime DateOfBirth { set; get; }

        public string DoctorName { set; get; }
        public string DoctorDepartment { set; get; }

        public List<PrescribedTestsViewmodel> Tests { set; get; }
    }

    public class PrescribedTestsViewmodel
    {
        [Display(Name = "Test Name")]
        public TestTypes TestType { set; get; }

        public string Name { get; set; }

        [Display(Name = "Patient Id")]
        public int PatientId{ get; set; }

        [Display(Name = "Patient Id")]
        public int MedicalTestTypeId { get; set; }

        public int MedicalTestId { set; get; }

        public int PrescriptionId { set; get; }

        public MedicalTestStatus Status { set; get; }
    }

    public class GetTestViewModel
    {
        public int PatientId { set; get; }
        public TestTypes TestType { set; get; }
        public int MedicalTestId { set; get; }
        public int PrescriptionId { set; get; }
    }
}

NazeeranHospitalManagement/Controllers/LabController.cs
using NazeeranHospitalManagement.Models;
using NazeeranHospitalManagement.ViewModels;
using NazeeranHospitalManagement.ViewModels.Enums;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace NazeeranHospitalManagement.Controllers
{
    [Authorize(Roles = "LabAttendent")]
    public class LabController : Controller
    {
        private NazeeranHospitalDbContext db = new NazeeranHospitalDbContext();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(int? patientId)
        {
            if (ModelState.IsValid)
            {
                if (patientId.HasValue)
                {
                    var patient = await db.Patients.FirstOrDefaultAsync(pat => pat.Id == patientId.Value);
                    var medicalTests = await db.MedicalTests.Where(test => test.Prescription.PatientId == patientId.Value)
                        .OrderByDescending(o => o.Id)
                        .Include(o => o.Prescription.Doctor.User)
                        .ToListAsync();

                        var model = new ViewLabTestsViewModel
                        {
                            PatientId = patientId.Value,
                            PatientName = patient.User.Name,
                            DoctorName = medicalTests.ElementAt(0).Prescription.Doctor.User.Name,
                            DateOfBirth = new DateTime(1992, 09, 07),
                            Tests = new List<PrescribedTestsViewmodel>()
                        };

                        model.Tests.AddRange(medicalTests.Select(test => new PrescribedTestsViewmodel
                        {
                            MedicalTestTypeId = test.MedicalTestTypeId,
                            PatientId = test.Prescription.PatientId,
                            TestType = (TestTypes)Enum.Parse(typeof(TestTypes), test.MedicalTestType.Name),
                            MedicalTestId = test.Id,
                            PrescriptionId = test.PrescriptionId,
                            Status = test.Status
                        }));

                        bool isAdded = false;
                        if (TempData.Keys.Contains("IsAdded"))
                            isAdded = (bool)TempData["IsAdded"];

                        return View("LabPrescribe", model);
                }
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddTestResult(GetTestViewModel testModel)
        {
            ViewBag.MedicalTestId = testModel.MedicalTestId;
            try
            {
                var medicalTest = await db.MedicalTests.FindAsync(testModel.MedicalTestId);

                if (medicalTest == null)
                {
                    ViewData["Errors"] = new List<string> { "Sorry, Something Wen Wrong While Getting Date...!!" };
                }
                else if (medicalTest.Status == MedicalTestStatus.Completed)
                {
                    ViewData["Errors"] = new List<string> { "Sorry, Test Result Is Already Entered...!!" };
                }
            }
            catch(Exception ex)
            {
                ex.ToString();
                ViewData["Errors"] = new List<string> { "Sorry, There Was An Errror While Getting Test Details...!!" };
            }

            switch (testModel.TestType)
            {
                case TestTypes.BloodCP:
                    var BloodCPModel = new BloodCP { PrescriptionId = testModel.PrescriptionId };
                    return View(testModel.TestType.ToString(), BloodCPModel);

                case TestTypes.Calcuim:
                    var CalcuimModel = new Calcium { PrescriptionId = testModel.PrescriptionId };
                    return View(testModel.TestType.ToString(), CalcuimModel);

                case TestTypes.CrossMatch:
                    var CrossMatchModel = new CrossMatch {  };
                    return View(testModel.TestType.ToString(), CrossMatchModel);

                case TestTypes.TFT:
                    var TFTModel = new TFT { PrescriptionId = testModel.PrescriptionId };
                    return View(testModel.TestType.ToString(), TFTModel);
            }

            return RedirectToActionPermanent("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BloodCP(BloodCP model, int? MedicalTestId)
        {
            ViewData["IsAdded"] = false;

            if (ModelState.IsValid && MedicalTestId.HasValue)
            {
                try
                {
                    var test = await db.MedicalTests.FirstOrDefaultAsync(t => t.Id == MedicalTestId.Value);

                    if(test == null)
                    {
                        ViewData["Errors"] = new List<string> { "Sorry, Something Wen Wrong While Getting Date...!!" };
                    }
                    else if (test.Status == MedicalTestStatus.Completed)
                    {
                        ViewData["Errors"] = new List<string> { "Sorry, Test Result Is Already Entered...!!" };
                    }
                    else if (test != null)
                    {
                        test.Status = MedicalTestStatus.Completed;
                        model.Status = MedicalTestStatus.Completed;

                        db.Entry(model).State = EntityState.Added;
                        db.Entry(test).State = EntityState.Modified;

                        await db.SaveChangesAsync();
                        ViewData["IsAdded"] = true;
                    }
                }
                catch (Exception ex)
                {
                    ex.ToString();
                    ViewData["Errors"] = new List<string> { "Sorry! An Error Occured While Updating Database...!!"};
                }
            }

            ViewBag.MedicalTestId = MedicalTestId.Value;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CrossMatch(CrossMatch model, int? MedicalTestId)
        {
            ViewData["IsAdded"] = false;

            if (ModelState.IsValid && MedicalTestId.HasValue)
            {
                try
                {
                    var test = await db.MedicalTests.FirstOrDefaultAsync(t => t.Id == MedicalTestId.Value);

                    if (test == null)
                    {
                        ViewData["Errors"] = new List<string> { "Sorry, Something Wen Wrong While Getting Data...!!" };
                    }
                    else if (test.Status == MedicalTestStatus.Completed)
                    {
                        ViewData["Errors"] = new List<string> { "Sorry, Test Result Is Already Entered...!!" };
                    }
                    else if (test != null)
                    {
                        test.Status = MedicalTestStatus.Completed;

                        db.Entry(model).State = EntityState.Added;
                        db.Entry(test).State = EntityState.Modified;

                        await db.SaveChangesAsync();
                        ViewData["IsAdded"] = true;
                    }
                }
                catch (Exception ex)
                {
                    ex.ToString();
                    ViewData["Errors"] = new List<string> { "Sorry! An Error Occured While Updating Database...!!" };

                }
            }

            ViewBag.MedicalTestId = MedicalTestId.Value;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> TFT(TFT model, int? MedicalTestId)
        {
            ViewData["IsAdded"] = false;

            if (ModelState.IsValid && MedicalTestId.HasValue)
            {
                try
                {
                    var test = await db.MedicalTests.FirstOrDefaultAsync(t => t.Id == MedicalTestId.Value);

                    if (test == null)
                    {
                        ViewData["Errors"] = new List<string> { "Sorry, Something Wen Wrong While Getting Date...!!" };
                    }
                    else if (test.Status == MedicalTestStatus.Completed)
                    {
                        ViewData["Errors"] = new List<string> { "Sorry, Test Result Is Already Entered...!!" };
                    }
                    else if (test != null)
                    {
                        test.Status = MedicalTestStatus.Completed;

                        db.Entry(model).State = EntityState.Added;
                        db.Entry(test).State = EntityState.Modified;

                        await db.SaveChangesAsync();
                        ViewData["IsAdded"] = true;
                    }
                }
                catch (Exception ex)
                {
                    ex.ToString();
                    ViewData["Errors"] = new List<string> { "Sorry! An Error Occured While Updating Database...!!" };
                }
            }

            ViewBag.MedicalTestId = MedicalTestId.Value;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Calcuim(Calcium model, int? MedicalTestId)
        {
            ViewData["IsAdded"] = false;

            if (ModelState.IsValid && MedicalTestId.HasValue)
            {
                try
                {
                    var test = await db.MedicalTests.FirstOrDefaultAsync(t => t.Id == MedicalTestId.Value);

                    if (test == null)
                    {
                        ViewData["Errors"] = new List<string> { "Sorry, Something Wen Wrong While Getting Date...!!" };
                    }

NazeeranHospitalManagement/Views/Lab/BloodCP.cshtml
@model BloodCP

@{
    ViewBag.Title = "BloodCP";
    Layout = "~/Views/Shared/_PrescribingMedicine.cshtml";
    Page.Title = "BloodCP";
    int MedicalTestId = ViewBag.MedicalTestId;
    bool IsAdded = false;

    if (ViewData.Keys.Contains("IsAdded"))
    {
        IsAdded = (bool)ViewData["IsAdded"];
    }

    List<string> Errors = ViewData["Errors"] as List<string>;
}

@if (IsAdded)
{
    <div class="hidden" id="alertUser">
        <p id="header-message">Success</p>
        <p id="main-message">Test Recod Is Upadted Successfully...!!</p>
        <p id="alert-type">success</p>
        <p id="confirm-button-class">btn-success</p>
    </div>
}

@if(Errors != null)
{
    foreach(var err in Errors)
    {
        <p class="text-danger">@err</p>
    }
}
else if(!IsAdded)
{
    <div>
        @using (Html.BeginForm("BloodCP", "Lab", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.PrescriptionId)
            <input type="hidden" name="MedicalTestId" value="@MedicalTestId" />

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true)
                <label>Normal Range : </label>
                <label>3.3 - 7.8 mg/dl</label>
                <div class="form-group">
                    @Html.LabelFor(model => model.Glucose2HRSABF, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Glucose2HRSABF, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Glucose2HRSABF)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <p class="text-danger">Test Result Is Added....!!</p>
}

NazeeranHospitalManagement/Views/Lab/Calcuim.cshtml
@model Calcium

@{
    ViewBag.Title = "Calcuim";
    Layout = "~/Views/Shared/_PrescribingMedicine.cshtml";
    Page.Title = "Calcuim";
    int MedicalTestId = ViewBag.MedicalTestId;
    bool IsAdded = false;

    if (ViewData.Keys.Contains("IsAdded"))
    {
        IsAdded = (bool)ViewData["IsAdded"];
    }

    List<string> Errors = ViewData["Errors"] as List<string>;
}

@if (IsAdded)
{
    <div class="hidden" id="alertUser">
        <p id="header-message">Success</p>
        <p id="main-message">Test Recod Is Upadted Successfully...!!</p>
        <p id="alert-type">success</p>
        <p id="confirm-button-class">btn-success</p>
    </div>
}

@if (Errors != null)
{
    foreach (var err in Errors)
    {
        <p class="text-danger">@err</p>
    }
}
else if (!IsAdded)
{
    <div>
        <label>Normal Range : </label>
        <label>8.6 - 10.3 mg/dl</label>
        @using (Html.BeginForm("Calcuim", "Lab", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.PrescriptionId)
            <input type="hidden" name="MedicalTestId" value="@MedicalTestId" />

            <div class="form-horizontal">

                @Html.ValidationSummary(true)


                <div class="form-group">
                    @Html.LabelFor(model => model.calcium1, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.calcium1, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.calcium1)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @if (IsAdded)
                        {
                            <input type="submit" value="Update" class="btn btn-info" />
                        }
                        else
                        {
                            <input type="submit" value="Save" class="btn btn-info" />
                        }
                    </div>
                </div>
            </div>
        }

    </div>
}
else
{
    <p class="text-danger">Test Result Is Added....!!</p>
}

NazeeranHospitalManagement/Views/Lab/CrossMatch.cshtml
@model CrossMatch

@{
    ViewBag.Title = "CrossMatch";
    Layout = "~/Views/Shared/_PrescribingMedicine.cshtml";
    Page.Title = "Cross Match";

    int MedicalTestId = ViewBag.MedicalTestId;
    bool IsAdded = false;
    if (ViewData.Keys.Contains("IsAdded"))
    {
        IsAdded = (bool)ViewData["IsAdded"];
    }

    List<string> Errors = ViewData["Errors"] as List<string>;
}

@if (IsAdded)
{
    <div class="hidden" id="alertUser">
        <p id="header-message">Success</p>
        <p id="main-message">Test Recod Is Upadted Successfully...!!</p>
        <p id="alert-type">success</p>
        <p id="confirm-button-class">btn-success</p>
    </div>
}

@if (Errors != null)
{
    foreach (var err in Errors)
    {
        <p class="text-danger">@err</p>
    }
}
else if(!IsAdded)
{
    <div>
        @using (Html.BeginForm("CrossMatch", "Lab", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.PrescriptionId)
            <input type="hidden" name="MedicalTestId" value="@MedicalTestId" />

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.MRNOfDonor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MRNOfDonor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MRNOfDonor)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NameOfDonor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NameOfDonor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NameOfDonor)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AgeOfDonor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AgeOfDonor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AgeOfDonor)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RelationOfDonorWithPatient, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.RelationOfDonorWithPatient, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RelationOfDonorWithPatient)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BloodBagNO, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BloodBagNO, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BloodBagNO)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PatientBloodGroup, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PatientBloodGroup, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PatientBloodGroup)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CrossMatchValue, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CrossMatchValue, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CrossMatchValue)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <p class="text-danger">Test Result Is Added....!!</p>
}

NazeeranHospitalManagement/Views/Lab/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PrescribingMedicine.cshtml";
    Page.Title = "Index";
}

<div class="viewPatient_top">
    <h4>Search Patient</h4>

    @using (Html.BeginForm("Index", "Lab", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="input-group">
            <input type="text" name="patientId" class="search-form" placeholder="Enter Patient Id"><span class="input-group-btn"></span>
            <button class="btn btn-default btn-round">Next</button>
        </div>
    }
</div>

NazeeranHospitalManagement/Views/Lab/LabPrescribe.cshtml
@model ViewLabTestsViewModel
@{
    ViewBag.Title = "LabPrescribe";
    Layout = "~/Views/Shared/_PrescribingMedicine.cshtml";
    Page.Title = "View Patients Tests";
    Age Age = Age.GetAge(Model.DateOfBirth, DateTime.Now);
}


@*<div class="well">
    <label>@Model.PatientId</label>
    <label>@Model.PatientName</label>
    <label>@Age.Years Years @Age.Months Months</label>
    <label>@Model.DoctorName</label>
</div>*@

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <label>Patient ID : </label>
            <label>@Model.PatientId</label>
            <br />
            <label>Patient Name : </label>
            <label>@Model.PatientName</label>
        </div>
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <label>Patient Age : </label>
            <label>@Age.Years Years @Age.Months Months</label>
            <br />
            <label>Doctor Name : </label>
            <label>@Model.DoctorName</label>
        </div>
    </div>
</div>

<div id="prescribedTest">
        <table id="prescribedMedicine" class="table table-striped table-bordered" cellspacing="0" width=20 style="margin-top:2em">
            <thead>
                <tr class="info">
                    <th>
                        @Html.DisplayNameFor(model => model.Tests.ElementAt(0).TestType)
                    </th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Tests)
                {
                    <tr>
                        @using (Html.BeginForm("AddTestResult", "Lab", FormMethod.Post, new { target = "_blank" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(modelItem => item.MedicalTestId)
                            <td>
                                @Html.DisplayFor(modelItem => item.TestType)
                            </td>
                            <td>
                                @item.Status.ToString()
                            </td>
                            <td>
                                @Html.HiddenFor(modelItem => item.PatientId)
                                @Html.HiddenFor(modelItem => item.TestType)
                                @Html.HiddenFor(modelItem => item.MedicalTestId)
                                @Html.HiddenFor(modelItem => item.PrescriptionId)
                                @if (item.Status != MedicalTestStatus.Completed)
                                {
                                    <button type="submit" class="btn btn-info">Enter Result</button>
                                }
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
</div>

NazeeranHospitalManagement/Views/Lab/TFT.cshtml
@model TFT

@{
    ViewBag.Title = "TFT";
    Layout = "~/Views/Shared/_PrescribingMedicine.cshtml";
    Page.Title = "TFT";
    int MedicalTestId = ViewBag.MedicalTestId;
    bool IsAdded = false;

    if (ViewData.Keys.Contains("IsAdded"))
    {
        IsAdded = (bool)ViewData["IsAdded"];
    }

    List<string> Errors = ViewData["Errors"] as List<string>;
}

@if (IsAdded)
{
    <div class="hidden" id="alertUser">
        <p id="header-message">Success</p>
        <p id="main-message">Test Recod Is Upadted Successfully...!!</p>
        <p id="alert-type">success</p>
        <p id="confirm-button-class">btn-success</p>
    </div>
}

@if (Errors != null)
{
    foreach (var err in Errors)
    {
        <p class="text-danger">@err</p>
    }
}
else if(!IsAdded)
{
    <div>
        @using (Html.BeginForm("TFT", "Lab", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.PrescriptionId)
            <input type="hidden" name="MedicalTestId" value="@MedicalTestId" />

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true)
                <label>Normal Range : </label>
                <label>40 - 181 mg/dl</label>
                <div class="form-group">
                    @Html.LabelFor(model => model.TotalT3, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TotalT3, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TotalT3)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TotalT4, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TotalT4, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TotalT4)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TSH, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TSH, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TSH)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    </div>
}
else
{
    <p class="text-danger">Test Result Is Added....!!</p>
}