NazeeranHospitalManagement/Models/Medicine.cs
using System;
using System.Collections.Generic;

namespace NazeeranHospitalManagement.Models
{
    public partial class Medicine
    {
        public Medicine()
        {
            this.PrescribedMedicines = new HashSet<PrescribedMedicine>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Potency { get; set; }
        public string ManufacturerName { get; set; }
        public DateTime ManufactuerDate { get; set; }
        public DateTime ExpiryDate { get; set; }
        public double PricePerUnit { get; set; }
        public int Quantity { get; set; }
        public string ChemicalComposition { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> QuantityThreshold { get; set; }
        public Nullable<DateTime> ExpiryThreshold { get; set; }
    
        public virtual ICollection<PrescribedMedicine> PrescribedMedicines { get; set; }
    }
}

NazeeranHospitalManagement/Controllers/MedicineController.cs
using Microsoft.AspNet.Identity;
using NazeeranHospitalManagement.Models;
using NazeeranHospitalManagement.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
using System.Web.UI.WebControls;

namespace NazeeranHospitalManagement.Controllers
{
    [HandleError]
    [Authorize(Roles = "Pharmacist")]
    public class MedicineController : Controller
    {
        private NazeeranHospitalDbContext db = new NazeeranHospitalDbContext();

        public ActionResult Index()
        {
            return View();
        }

        [WebMethod]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Display()
        {
            return View(await db.Medicines.ToListAsync());
        }

        public async Task<ActionResult> GetMed(string Name, string ManufacturerName, string ChemicalComposition)
        {
            var Medicines = await db.Medicines.ToListAsync();

            if (!string.IsNullOrEmpty(Name))
            {
                Medicines = Medicines.Where(med => med.Name.ToLower().Contains(Name.ToLower())).ToList();
            }

            if (!string.IsNullOrEmpty(ManufacturerName))
            {
                Medicines = Medicines.Where(med => med.ManufacturerName.ToLower().Contains(ManufacturerName.ToLower())).ToList();
            }

            if (!string.IsNullOrEmpty(ChemicalComposition))
            {
                Medicines = Medicines.Where(med => med.ChemicalComposition.ToLower().Contains(ChemicalComposition.ToLower())).ToList();
            }

            return View("Display", Medicines);
        }

        public async Task<ActionResult> GetMedUpdate(string Name, string ManufacturerName, string ChemicalComposition)
        {
            var Medicines = await db.Medicines.ToListAsync();

            if (!string.IsNullOrEmpty(Name))
            {
                Medicines = Medicines.Where(med => med.Name.ToLower().Contains(Name.ToLower())).ToList();
            }

            if (!string.IsNullOrEmpty(ManufacturerName))
            {
                Medicines = Medicines.Where(med => med.ManufacturerName.ToLower().Contains(ManufacturerName.ToLower())).ToList();
            }

            if (!string.IsNullOrEmpty(ChemicalComposition))
            {
                Medicines = Medicines.Where(med => med.ChemicalComposition.ToLower().Contains(ChemicalComposition.ToLower())).ToList();
            }

            return View("Update", Medicines);
        }

        public async Task<JsonResult> SearchMedidicne(string term = "")
        {
            var MedicinesList = await db.Medicines
                .Where(med => med.Name.ToLower().Contains(term.ToLower()))
                .ToListAsync();

            var Lists = MedicinesList.Select(med => new
            {
                label = $"{med.Name} {med.Type} {med.Potency}",
                value = med.Name,
                medicineId = med.Id
            });

            return Json(Lists, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> SearchMedidicneByManu(string term = "")
        {
            var MedicinesList = db.Medicines
                .Where(med => med.ManufacturerName.ToLower().Contains(term.ToLower()))
                .Select(med => new
                {
                    label = med.ManufacturerName,
                    value = med.ManufacturerName,
                    medicineId = med.Id
                });

            return Json(await MedicinesList.ToListAsync(), JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> SearchMedidicneByChemi(string term = "")
        {
            var MedicinesList = db.Medicines
                .Where(med => med.ChemicalComposition.ToLower().Contains(term.ToLower()))
                .Select(med => new
                {
                    label = med.ChemicalComposition,
                    value = med.ChemicalComposition,
                    medicineId = med.Id
                });

            return Json(await MedicinesList.ToListAsync(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ViewPatient()
        {
            if (TempData.ContainsKey("ErrorWhilePrescriptionAdded"))
                ViewData["ErrorWhilePrescriptionAdded"] = true;
            else if (TempData.ContainsKey("PrescriptionAdded"))
                ViewData["PrescriptionAdded"] = true;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ViewPatient(int? idd)
        {
            if (ModelState.IsValid)
            {
                if (idd.HasValue)
                {
                    var prescription = db.Prescriptions.Where(p => p.PatientId == idd.Value).OrderByDescending(o => o.Id).ToList();
                    if (prescription.Count > 0)
                    {
                        var m = new A();
                        //m1.prescription_id = prescription[0].Id;
                        int Id = prescription[0].Id;
                        var prescribeMedicine = db.PrescribedMedicines.Where(k => k.PrescriptionId == Id).ToList();

                        m.idd = idd.Value;
                        m.m1 = new List<PrescribeMedicinesViewmodel>();
                        for (int i = 0; i < prescribeMedicine.Count; i++)
                        {
                            PrescribeMedicinesViewmodel m1 = new PrescribeMedicinesViewmodel();
                            m1.medicine_id = prescribeMedicine[i].MedicineId;
                            m1.medicine_quantity = prescribeMedicine[i].Quantity;
                            m1.medicine_time = prescribeMedicine[i].Time;
                            m1.medicine_noOfday = prescribeMedicine[i].NoOfDays;


                            //for (int j = 0; j < prescribeMedicine.Count; j++)
                            if (prescribeMedicine.Count > 0)
                            {
                                var prescribeMedicineName = db.Medicines.Where(n => n.Id == m1.medicine_id).ToList();
                                m1.medicine_name = prescribeMedicineName[0].Name;
                                m1.TypeM = prescribeMedicineName[0].Type;
                                m1.PotencyM = prescribeMedicineName[0].Potency;
                                m1.medicine_price = prescribeMedicineName[0].PricePerUnit;
                                m1.price = (m1.medicine_quantity * m1.medicine_price);
                                m.m1.Add(m1);
                            }
                        }

                        return View("GivePrescribe", m);

                    }
                    else
                    {
                        return View();
                    }
                }
            }
            return View();
        }

        public ActionResult bill()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> bill(A model)
        {
            if (ModelState.IsValid)
            {
                foreach (var m in model.m1)
                {
                    //var MedicineName = await db.Medicines.FirstOrDefaultAsync(n => n.Name == m.medicine_name);
                    //MedicineName.Quantity = MedicineName.Quantity - m.medicine_quantity;

                    //db.Entry(MedicineName).Status = EntityState.Modified;
                }

                try
                {
                    var bill = new MedicineBill { PatientId = model.idd, PharmacistId = User.Identity.GetUserId(), Amount = 1, BillTime = DateTime.Now };
                    db.Entry(bill).State = EntityState.Added;

                    await db.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    ex.ToString();
                }

                return View("bill", model);
            }
            return RedirectToAction("GivePrescribe", model);
        }

        public ActionResult SaveBill(A model)
        {
            TryUpdateModel(model, new[] { "idd" });
            TryValidateModel(model);

            if (ModelState.IsValid)
            {
                double result = 0.0;
                double result1 = 0.0;
                for (int i = 0; i < model.m1.Count; i++)
                {
                    if (model.m1[i].medicine_quantity > 0)
                    {
                        string s = model.m1[i].medicine_name;
                        var MedicineName = db.Medicines.FirstOrDefault(n => n.Name == s);
                        MedicineName.Quantity = MedicineName.Quantity - model.m1[i].medicine_quantity;
                        db.Entry(MedicineName).State = EntityState.Modified;
                        result1 = model.m1[i].medicine_price * model.m1[i].medicine_quantity;
                        result += result1;
                    }

                }
                var bill = new MedicineBill { PatientId = model.idd, PharmacistId = User.Identity.GetUserId(), Amount = result, BillTime = DateTime.Now };
                db.Entry(bill).State = EntityState.Added;
                try
                {
                    db.SaveChanges();
                    TempData["PrescriptionAdded"] = true;
                    //return new ViewAsPdf("bill", model)
                    //{
                    //    FileName = "BillNumber.pdf"
                    //};
                }
                catch (Exception ex)
                {
                    TempData["ErrorWhilePrescriptionAdded"] = true;
                    ex.ToString();
                }
            }

            return RedirectToAction("ViewPatient");
        }

        //public ActionResult GeneratePDF(A model, FormCollection fc)
        //{

NazeeranHospitalManagement/Views/Medicine/Display.cshtml
@model IEnumerable<Medicine>
@{
    ViewBag.Title = "Display";
    Layout = "~/Views/Shared/_PharmacistLayout.cshtml";
    Page.Title = "Medicine Stock";
}

<form method="get" action="@Url.Action("GetMed", "Medicine")"
      data-ppims-ajax="true" data-ppims-target="#prescribed-medicines-panel table tbody">

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="custom-search-input">
                    <div class="input-group">
                        <input type="text" id="ab12" name="Name" class="search-query form-control" placeholder="Search by Name" data-ppims-autocomplete="@Url.Action("SearchMedidicne", "Medicine")" />
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-default">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="input-group">
                    <input type="text" name="ManufacturerName" class="search-query2 form-control" placeholder="Search by Manufacturer Name" data-ppims-autocomplete="@Url.Action("SearchMedidicneByManu", "Medicine")" />
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </div>

            <div class="col-md-4">
                <div class="input-group">
                    <input type="text" name="ChemicalComposition" class="search-query1 form-control" placeholder="Search by Chemical Composition" data-ppims-autocomplete="@Url.Action("SearchMedidicneByChemi", "Medicine")" />
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </div>

        </div>
    </div>
</form>

<table id="example" class="table table-striped table-bordered" cellspacing="0" width=20>
    <thead>
        <tr class="info">
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManufacturerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BatchNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChemicalComposition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuantityThreshold)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManufactuerDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpiryDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpiryThreshold)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PricePerUnit)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            if (item.QuantityThreshold > item.Quantity || DateTime.Now > item.ExpiryThreshold)
            {
                if (DateTime.Now > item.ExpiryDate)
                {
                    item.Quantity = 0;
                    <tr id="redd11">
                        <td>
                            <div>
                                @Html.DisplayFor(modelItem => item.Name)
                                @Html.DisplayFor(modelItem => item.Type)
                                @Html.DisplayFor(modelItem => item.Potency)
                            </div>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ManufacturerName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BatchNo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ChemicalComposition)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.QuantityThreshold)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ManufactuerDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ExpiryDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ExpiryThreshold)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PricePerUnit)
                        </td>
                        <td class="btnTable" width="120px">
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-info btn-xs" })
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-xs" })
                        </td>
                    </tr>
                }
                else
                {
                    <tr id="redd">
                        <td>
                            <div>
                                @Html.DisplayFor(modelItem => item.Name)
                                @Html.DisplayFor(modelItem => item.Type)
                                @Html.DisplayFor(modelItem => item.Potency)
                            </div>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ManufacturerName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BatchNo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ChemicalComposition)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.QuantityThreshold)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ManufactuerDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ExpiryDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ExpiryThreshold)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PricePerUnit)
                        </td>
                        <td class="btnTable" width="120px">
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-info btn-xs" })
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-xs" })
                        </td>
                    </tr>
                }

            }
            else
            {
                <tr>
                    <td>
                        <div>
                            @Html.DisplayFor(modelItem => item.Name)
                            @Html.DisplayFor(modelItem => item.Type)
                            @Html.DisplayFor(modelItem => item.Potency)
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ManufacturerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BatchNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ChemicalComposition)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QuantityThreshold)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ManufactuerDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpiryDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpiryThreshold)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PricePerUnit)
                    </td>
                    <td class="btnTable" width="120px">
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-info btn-xs" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-xs" })
                    </td>
                </tr>
            }
        }
    </tbody>

</table>

<p>
    @*Medicine Name: @Html.TextBox("Name", null, new { @class = "search-name" })<br />
        Chemical Composition: @Html.TextBox("ChemicalComposition", null, new { @class = "search-chemical" })<br />
        Manufacturer Name: @Html.TextBox("ManufacturerName", null, new { @class = "search-Manuf" })<br />
        <input type="submit" value="Search" class="search-btn" />*@
</p>
@*}*@

NazeeranHospitalManagement/Views/Medicine/GivePrescribe.cshtml
@model A

@{
    ViewBag.Title = "GivePrescribe";
    Layout = "~/Views/Shared/_PharmacistLayout.cshtml";
    Page.Title = "Medicine Subscription";
}

<div data-otf-target>
    @using (Html.BeginForm("SaveBill", "Medicine", FormMethod.Post, new { target = "_blank" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(modelItem => Model.idd)
        <table id="prescribedMedicine" class="table table-striped table-bordered" cellspacing="0" width="100">
            <thead>
                <tr class="info">
                    <th>
                        @Html.DisplayNameFor(model => model.m1.ElementAt(0).medicine_name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.m1.ElementAt(0).medicine_time)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.m1.ElementAt(0).medicine_noOfday)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.m1.ElementAt(0).medicine_quantity)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.m1.ElementAt(0).medicine_price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.m1.ElementAt(0).price)
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.m1)
                {
                    <tr>
                        <td>
                            @Html.HiddenFor(modelItem => item.medicine_name)
                            @Html.DisplayFor(modelItem => item.medicine_name)
                            @Html.DisplayFor(modelItem => item.TypeM)
                            @Html.DisplayFor(modelItem => item.PotencyM)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.medicine_time)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.medicine_noOfday)
                        </td>
                        <td>
                            @*@Html.HiddenFor(modelItem => item.medicine_quantity)*@
                            @Html.EditorFor(modelItem => item.medicine_quantity, new { @class = "quantity_box" })
                            <input type="hidden" name="inStockQuantity" value="@item.medicine_quantity" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.medicine_price)
                            @Html.HiddenFor(modelItem => item.medicine_price)
                        </td>
                        <td>
                            <label id="subTotal">@item.price</label>
                            @Html.HiddenFor(modelItem => item.price)
                            @*@Html.DisplayFor(modelItem => item.price)*@
                        </td>
                    </tr>
                }
            </tbody>

            <tfoot>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <label class="right">Total:</label>
                        <label id="totalBill"></label>
                    </td>
                </tr>
            </tfoot>
        </table>
    <input type="button" onclick="window.location.href='@Url.Action("ViewPatient")'" value="Back" class="btn btn-info" />

    <input type="submit" value="Save..." class="btn btn-info" />

    @*<input type="button" onclick="window.location.href='@Url.Action("SendMail")'" value="Send Medicine Prescription" class="btn btn-info" />*@
        @*<input type="button" value="Save Bill" class="btn btn-info search-btn1" id="btnSaveBill"/>
        <input type="button" value="Print Bill" class="btn btn-info search-btn1" id="btnPrintBill" />*@
    }
</div>

NazeeranHospitalManagement/Views/Medicine/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_PharmacistDashboard.cshtml";
    Page.Title = "Dashboard";
}

NazeeranHospitalManagement/Views/Medicine/Laboratorists.cshtml
@{
    ViewBag.Title = "Laboratorists";
    Layout = "~/Views/Shared/_Laboratorists.cshtml";
    Page.Title = "Laboratorists";
}

NazeeranHospitalManagement/Views/Medicine/SendMail.cshtml
@model MailModel
@{
    ViewBag.Title = "Mail";
    Layout = "~/Views/Shared/_PharmacistLayout.cshtml";
    Page.Title = "Send Prescription";
}
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script>
    $(document).ready(function () {
        if ('@ViewBag.Message' == 'Sent') {
            alert('Mail has been sent successfully');
        }
    });
</script>
<fieldset>
    @using (@Html.BeginForm("SendMail", "Medicine", FormMethod.Post, new { @id = "form1", @enctype = "multipart/form-data" }))
    {
    @Html.ValidationSummary()


    <table class="table table-striped">
        <tr>
            <td>
                To:
            </td>
            <td>
                @Html.TextBoxFor(m => m.To)

            </td>
        </tr>
        <tr>
            <td>
                Subject:
            </td>
            <td>
                @Html.TextBoxFor(m => m.Subject)
            </td>
        </tr>
        <tr>
            <td>
                Attachment
            </td>
            <td>
                <input type="file" name="fileUploader" />
            </td>
        </tr>
        <tr>
            <td>
                Body:
            </td>
            <td>
                @Html.TextAreaFor(m => m.Body)
            </td>
        </tr>
    </table>
    <input type="submit" value="Send" class="btn btn-info" />
    }
</fieldset>

NazeeranHospitalManagement/Views/Medicine/ViewPatient.cshtml
@{
    ViewBag.Title = "View Patient";
    Layout = "~/Views/Shared/_PharmacistLayout.cshtml";
    Page.Title = "Patient Prescription";

    var errorWhilePrescriptionAdded = false;
    if (ViewData.ContainsKey("ErrorWhilePrescriptionAdded"))
    {
        errorWhilePrescriptionAdded = (bool)ViewData.ContainsKey("ErrorWhilePrescriptionAdded");
    }

    var prescriptionAdded = false;
    if (ViewData.ContainsKey("PrescriptionAdded"))
    {
        prescriptionAdded = (bool)ViewData.ContainsKey("PrescriptionAdded");
    }
}

@if (errorWhilePrescriptionAdded)
{
    <div id="alertUser" class="hidden">
        <p id="header-message">Error Occured.</p>
        <p id="main-message">An Error Occured While Saving medicine details.</p>
        <p id="alert-type">info</p>
        <p id="confirm-button-class"></p>
    </div>
}
else if (prescriptionAdded)
{
    <div id="alertUser" class="hidden">
        <p id="header-message">Success.</p>
        <p id="main-message">medicine details are added sucessfully.</p>
        <p id="alert-type">success</p>
        <p id="confirm-button-class"></p>
    </div>
}

<div class="viewPatient_top">
    <h4>Search Patient</h4>

    @using (Html.BeginForm("ViewPatient", "Medicine", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @*<p>*@
            <div class="input-group">
                <input type="text" name="idd" class="search-form" placeholder="Enter Patient Id"><span class="input-group-btn"></span>
                <button class="btn btn-default btn-round">Next</button>
            </div>
        @*</p>*@
            @*<div class="row">
                <div class="col-md-4">
                    <div class="custom-search-input-view">
                        <div class="input-group">
                            <input type="text" name="idd" class="  search-query-view form-control" placeholder="Search by Id" />
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-default">
                                    <span class=" glyphicon glyphicon-search"></span>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="input-group">
                        <input type="text" name="CNIC" class="  search-query1-view form-control" placeholder="Search by CNIC" />
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-default">
                                <span class=" glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="input-group">
                        <input type="text" name="Email" class="  search-query2-view form-control" placeholder="Search by Email" />
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-default">
                                <span class=" glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                </div>
            </div>*@
    }
</div>