NazeeranHospitalManagement/Models/Appointment.cs
using NazeeranHospitalManagement.ViewModels.Enums;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace NazeeranHospitalManagement.Models
{
    public partial class Appointment
    {
        public int Id { get; set; }
        public int AppointmentNo { get; set; }
        public DateTime Date { get; set; }
        public TimeSpan Time { get; set; }
        public AppointmentStatus Status { get; set; }

        [ForeignKey("Doctor")]
        public int DoctorId { get; set; }
        public virtual Doctor Doctor { get; set; }

        [ForeignKey("Patient")]
        public int PatientId { get; set; }
        public virtual Patient Patient { get; set; }
    }
}

NazeeranHospitalManagement/Controllers/GetAppointmentController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using NazeeranHospitalManagement.Models;
using NazeeranHospitalManagement.Models.Helpers;
using NazeeranHospitalManagement.ViewModels;
using NazeeranHospitalManagement.ViewModels.Enums;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace NazeeranHospitalManagement.Controllers
{
    public class GetAppointmentController : Controller
    {
        private NazeeranHospitalDbContext db = new NazeeranHospitalDbContext();
        private const string SearchScheduleBindParams = "DepartmentId,DoctorName,Date,SearchOption,FilterOption";

        [HttpGet]
        public async Task<ActionResult> SearchSchedule(SearchScheduleViewModel model)
        {
            // Set the default option to be SelectAnOption for the Search Option!
            model.SearchOption = SearchBy.SelectAnOption;

            // Get List of all departments...!!
            model.DepartmentList = await this.GetDepartments();

            // Set the SearchAppointmentViewModel an empty object!
            model.SearchAppointmentViewModel = new SearchAppointmentViewModel();

            if (model.WantCancelling)
            {
                model.OldAppointment = await GetAppointmentDetails(model.OldAppointmentId);
            }

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> GetSchedule(SearchScheduleViewModel model)
        {
            var Date = new DateTime();
            if (DateTime.TryParse(this.Request.QueryString["Date"], out Date))
            {
                model.Date = Date;
            }

            if (model.WantCancelling)
            {
                model.OldAppointment = await GetAppointmentDetails(model.OldAppointmentId);
            }

            // Get the list of DoctorSchedule that meets the selected criteria by the user!
            model.DoctorSchedule = await this.GetDoctorSchedule(model);

            // Get the list of all departments!
            model.DepartmentList = await this.GetDepartments();

            if (model.FilterOption == SearchBy.Dates || model.FilterOption == SearchBy.Department || model.FilterOption == SearchBy.Name)
            {
                // Filter doctor schedules according to the user criteria!
                await FilterDoctorSchedule(model);

                // If filter option is not 0, then set the IsFiltered to true to indicate that the search has been performed!
                model.IsFiltered = true;
            }

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> ViewSchedule(GetScheduleViewModel model)
        {
            var doctor = await db.Doctors.FirstOrDefaultAsync(doc => doc.UserId.Equals(model.DoctorId));
            var scheduleModel = new DoctorScheduleViewModel();
            scheduleModel.GetScheduleModel = model ?? new GetScheduleViewModel();
            scheduleModel.Appointments = new List<DoctorAppointmentsViewModel>();
            scheduleModel.WantCancelling = model.WantCancelling;

            if (doctor != null)
            {
                this.CreateDates(model);
                var doctorAppointments = doctor.Appointments.Where(
                    app => app.Date.Date >= model.StartDate.Date &&
                    app.Date.Date <= model.EndDate.Date &&
                    (app.Status == AppointmentStatus.Pending || app.Status == AppointmentStatus.Scheduled));

                int totalDays = (model.EndDate - model.StartDate).Days;
                var appointmentSlots = new List<DoctorAppointmentsViewModel>();
                for (var dayNo = 0; dayNo < totalDays; dayNo++)
                {
                    var day = (WeekDay)((int)model.StartDate.DayOfWeek);
                    var date = model.StartDate;
                    var schedule = doctor.DoctorSchedule.FirstOrDefault(sch => sch.Day == day);
                    var slots = GetAppointmentSlot(doctorAppointments, schedule, doctor.AverageTime, model.StartDate);
                    appointmentSlots.Add(new DoctorAppointmentsViewModel
                    {
                        Day = day,
                        Date = date,
                        AppointmentSlots = slots
                    });
                    model.StartDate = model.StartDate.AddDays(1);
                }

                scheduleModel.Appointments = appointmentSlots;
                scheduleModel.DoctorName = doctor.User.Name;
                scheduleModel.OldAppointmentId = -1;

                if (scheduleModel.WantCancelling)
                {
                    scheduleModel.OldAppointmentId = model.OldAppointmentId;
                    scheduleModel.OldAppointment = await this.GetAppointmentDetails(model.OldAppointmentId);
                    scheduleModel.BookAppointmentViewModel = new BookAppointmentViewModel
                    {
                        Status = scheduleModel.OldAppointment.Status,
                        PatientName = scheduleModel.OldAppointment.PatientName,
                        Cnic = scheduleModel.OldAppointment.PatientCnic,
                        PatientId = scheduleModel.OldAppointment.PatientId,
                        Email = scheduleModel.OldAppointment.PatientEmail,
                        ContactNo = scheduleModel.OldAppointment.PatientContactNo,
                        Gender = scheduleModel.OldAppointment.PatientGender
                    };
                }
            }

            // If doctor Is null Create A New List For Errors...!! Add Any Error To The Errors List To Inform The User...!!
            scheduleModel.Errors = scheduleModel.Errors ?? new List<string>();
            AddModelErrors(scheduleModel, ModelState);

            return View(scheduleModel);
        }

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BookAppointment(BookAppointmentViewModel model)
        {
            model.Errors = model.Errors ?? new List<string>();
            model.IsAppointmentBook = false;

            var patient = await SavePatient(model);

            if (patient == null)
                return View(model);

            model.PatientId = patient.Id;
            var doctor = await db.Doctors.SingleOrDefaultAsync(doc => doc.UserId.Equals(model.DoctorId));

            if (await IsAlreadyAppointmentBooked(patient, doctor, model.Date))
            {
                model.Errors.Add("Sorry, You Already Have An Appointment With This Doctor!");
                model.Errors.Add("You Can Not Have Multiple DoctorSchedule With The Same Doctor On The Same Day!");
            }
            else if (doctor != null)
            {
                var scheduledAppointment = await GetScheduledAppointment(model, doctor);
                scheduledAppointment.PatientId = patient.Id;

                try
                {
                    db.Entry(scheduledAppointment).State = model.OldAppointmentId > 0 ? EntityState.Modified : EntityState.Added;
                    await db.SaveChangesAsync();

                    model.IsAppointmentBook = true;
                    model.AppointmentId = scheduledAppointment.Id;
                    model.AppointmentNo = scheduledAppointment.AppointmentNo;
                    model.DoctorName = doctor.User.Name;
                    model.Status = AppointmentStatus.Pending;

                    // Send Message To The User About Appointment...!!
                    await SendMessage(model);
                }
                catch (Exception ex)
                {
                    ex.ToString();
                    model.Errors.Add("Sorry, There Was An Error While Booking Appointment...!!!");
                    model.Errors.Add("Please Try Again Or Contact To The Admin If Problem Persists..!!!");
                }
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SearchAppointment(SearchAppointmentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToActionPermanent("SearchSchedule");
            }

            Patient patient = null;

            if (!string.IsNullOrEmpty(model.Cnic))
                patient = await db.Patients.FirstOrDefaultAsync(pat => pat.User.Cnic == model.Cnic);

            if (patient == null)
            {
                model.IsFound = false;
            }
            else
            {
                var appointment = await db.Appointments.FirstOrDefaultAsync(app => app.AppointmentNo == model.AppointmentId && app.PatientId == patient.Id);

                model.IsFound = (appointment != null);

                if (model.IsFound)
                {
                    var isOverDate = (appointment.Date.Date < DateTime.Now.Date) && (appointment.Time.Hours < DateTime.Now.Hour && appointment.Time.Minutes < DateTime.Now.Minute);
                    var doctor = await db.Doctors.FirstOrDefaultAsync(doc => doc.Id == appointment.DoctorId);

                    model.AppointmentId = appointment.Id;
                    model.AppointmentNo = appointment.AppointmentNo;
                    model.Date = appointment.Date;
                    model.DoctorName = doctor.User.Name;
                    model.State = isOverDate ? AppointmentStatus.OverDate : appointment.Status;
                    model.Time = appointment.Time;
                    model.Cnic = patient.User.Cnic;
                }
            }

            return View(model);
        }

        [NonAction]
        public async Task<ViewAppointmentViewModel> GetAppointmentDetails(int AppointmentId)
        {
            var appointment = await db.Appointments.FirstOrDefaultAsync(app => app.AppointmentNo == AppointmentId);
            ViewAppointmentViewModel model = null;

NazeeranHospitalManagement/Views/GetAppointment/Appointment.cshtml
@model ViewAppointmentViewModel

@{
    ViewBag.Title = "Appointment";
    Layout = NazeeranHospitalManagementConstants.LayoutNameConst.DefaultLayout;
}
<div class="container-fluid">
    <div class="container">
        <div class="shadow-box min-padding-all min-top-margin min-bottom-margin">
            <h2 class="text-center">Appointment Details</h2>
            @using (Html.BeginForm("Cancel", "GetAppointment", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.AppointmentId)
                <div class="">
                    <h4 class="text-center">Your Appointment Details!</h4>
                    <hr />
                    <dl class="dl-horizontal">

                        <dt>
                            @Html.DisplayNameFor(model => model.DoctorName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.DoctorName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.DepartmentName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.DepartmentName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.AppointmentTime)
                        </dt>

                        <dd>
                            @{ var Time = Model.AppointmentTime.ToShortTimeString(); }
                            @Html.DisplayFor(model => Time)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.PatientName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.PatientName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Status)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Status)
                        </dd>
                    </dl>
                </div>

                <div class="min-top-margin">
                    @*<button type="submit" class="btn btn-danger pull-right">
                            <i class="glyphicon glyphicon-remove"></i> Cancel
                        </button>*@
                </div>
                <div class="clearfix"></div>
                                }
        </div>
    </div>
</div>

NazeeranHospitalManagement/Views/GetAppointment/Cancel.cshtml
@model ViewAppointmentViewModel

@{
    ViewBag.Title = "Cancel";
    Layout = NazeeranHospitalManagementConstants.LayoutNameConst.DefaultLayout;
}
<div class="container-fluid">
    <div class="container">
        <div class="shadow-box min-padding-all min-top-margin min-bottom-margin">
            <h2 class="text-center">Appointment Details</h2>
            <div class="">
                <h4 class="text-center">Your Appointment Details!</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.DoctorName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DoctorName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DepartmentName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DepartmentName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.AppointmentTime)
                    </dt>

                    <dd>
                        @{ var Time = Model.AppointmentTime.ToShortTimeString(); }
                        @Html.DisplayFor(model => Time)
                    </dd>

                    <dt>
                        Appointment Date
                    </dt>

                    <dd>
                        @{ var Date = Model.AppointmentTime.ToLongDateString(); }
                        @Html.DisplayFor(model => Date)
                    </dd>

                    <dt>
                        Appointment Day
                    </dt>

                    <dd>
                        @{ var Day = Model.AppointmentTime.DayOfWeek.ToString(); }
                        @Html.DisplayFor(model => Day)
                    </dd>


                    <dt>
                        @Html.DisplayNameFor(model => model.PatientName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PatientName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Status)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                </dl>

                <div class="min-top-margin">
                    @using (Html.BeginForm("Cancel", "GetAppointment", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.AppointmentId)
                        <button type="submit" class="btn btn-danger pull-right">
                            <i class="glyphicon glyphicon-remove"></i> Cancel
                        </button>
                    }
                </div>
                <div class="clearfix"></div>

            </div>
        </div>
    </div>
</div>

NazeeranHospitalManagement/Views/GetAppointment/FindAppointment.cshtml
@model SearchAppointmentViewModel

@{
    ViewBag.Title = "Search Appointment";
    Layout = NazeeranHospitalManagementConstants.LayoutNameConst.DefaultLayout;
}

<div class="col-md-10 middle-align min-heigth-box">
    <div class="container">
        <div class="shadow-box min-top-margin">
            <div class="min-padding-all">
                @using (Html.BeginForm("SearchAppointment", "GetAppointment", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.CheckBoxFor(model => Model.WantCancelling, new { @class = "hidden" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.AppointmentId, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.AppointmentId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AppointmentId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Cnic, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Cnic, new { htmlAttributes = new { @class = "form-control mask-cnic" } })
                                @Html.ValidationMessageFor(model => model.Cnic, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Search" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

NazeeranHospitalManagement/Views/GetAppointment/SearchAppointment.cshtml
@model SearchAppointmentViewModel

@{
    ViewBag.Title = "SearchAppointment";
    Layout = NazeeranHospitalManagementConstants.LayoutNameConst.DefaultLayout;
}

<h2 class="text-center">Appointment Details</h2>

@if (Model.IsFound)
{
    <div class="container">
        <div class="min-padding-all">
            <div class="">
                <div class="shadow-box">
                    <div class="min-padding-all">
                        <dl class="dl-horizontal">
                            <dt>@Html.DisplayNameFor(model => model.AppointmentId)</dt>
                            <dd>@Html.DisplayFor(model => model.AppointmentId)</dd>

                            <dt>@Html.DisplayNameFor(model => model.AppointmentNo)</dt>
                            <dd>@Html.DisplayFor(model => model.AppointmentNo)</dd>

                            <dt>Patient Cnic</dt>
                            <dd>@Html.DisplayFor(model => model.Cnic)</dd>

                            <dt>@Html.DisplayNameFor(model => model.DoctorName)</dt>
                            <dd>@Html.DisplayFor(model => model.DoctorName)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Date)</dt>
                            <dd>@Html.DisplayFor(model => model.Date)</dd>

                            <dt>@Html.DisplayNameFor(model => model.Time)</dt>
                            <dd>@Html.DisplayFor(model => model.Time) PST</dd>

                            <dt>Appointment Status.</dt>
                            <dd>@Html.DisplayFor(model => model.State)</dd>
                        </dl>
                    </div>

                    <div class="min-padding-all">
                        <div class="hidden" id="appointmentDetails">
                            @Html.HiddenFor(model => model.AppointmentId)
                            @Html.AntiForgeryToken()
                        </div>
                        @if (Model.State == AppointmentStatus.Scheduled || Model.State == AppointmentStatus.Pending)
                        {
                            if (Model.WantCancelling)
                            {
                                using (Html.BeginForm("SearchSchedule", "GetAppointment", FormMethod.Get, new { @class = "form-inline" }))
                                {
                                    @Html.HiddenFor(modelItem => Model.AppointmentId, new { Name = "OldAppointmentId" })
                                    @Html.HiddenFor(model => Model.WantCancelling)
                                    <button type="submit" value="Reschedule" class="btn btn-success hvr-sweep-to-right" id="btnRescheduleAppointment">Reschedule</button>
                                }
                            }
                            else
                            {
                                <button type="button" value="Cancel" class="btn btn-success hvr-sweep-to-right" id="btnCancelAppointment">Cancel</button>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

}
else
{
    <div class="min-heigth-box min-padding-all">
        <div class="shadow-box min-padding-all">
            <p class="text-danger text-center">
                Sorry! No Appointment Is Found...!!!<br />
                Enter A Valid Cnic and Appointment Id.
            </p>
        </div>
    </div>
}

NazeeranHospitalManagement/Views/GetAppointment/_PatientDetails.cshtml
@model BookAppointmentViewModel

@{
    Layout = null;
}

<!-- Modal -->
<div id="patientDetailsModel" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                @if (Model.OldAppointmentId <= 0)
                {
                    @:<h4 class="modal-title">Please, Enter your details here....!!</h4>
                }
                else
                {
                    @:<h4 class="modal-title">Your details are...!!</h4>
                }
            </div>

            <div class="modal-body">
                <div>
                    @using (Html.BeginForm("BookAppointment", "GetAppointment", FormMethod.Post, new { id = "viewSlotsForm" }))
                    {
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="hidden">
                            @Html.HiddenFor(model => model.DoctorId)
                            @Html.HiddenFor(model => model.Day)
                            @Html.HiddenFor(model => model.Date)
                            @Html.HiddenFor(model => model.SlotNo)
                            @Html.HiddenFor(model => model.OldAppointmentId)
                            @Html.AntiForgeryToken()
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">Patient Name</span>
                                @Html.EditorFor(model => model.PatientName, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="col-md-12">
                                @Html.ValidationMessageFor(modelItem => Model.PatientName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">Cnic</span>
                                @Html.EditorFor(model => model.Cnic, new { htmlAttributes = new { @class = "form-control mask-cnic" } })
                            </div>
                            <div class="col-md-12">
                                @Html.ValidationMessageFor(modelItem => Model.Cnic, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">Gender</span>
                                <select class="form-control" name="Gender">
                                    <option value="0">Male</option>
                                    <option value="1">Female</option>
                                </select>
                                <div class="col-md-12">
                                    @Html.ValidationMessageFor(modelItem => Model.Gender, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">Email</span>
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="col-md-12">
                                @Html.ValidationMessageFor(modelItem => Model.Email, "", new { @class = "text-danger" })
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">Contact No</span>
                                @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control mask-phone-no" } })
                            </div>
                            <div class="col-md-12">
                                @Html.ValidationMessageFor(modelItem => Model.ContactNo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    }
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-success btn-lg pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success btn-lg pull-right" id="btnProceed">
                    @if (Model.OldAppointmentId <= 0)
                    {
                        @:Book Appointment
                    }
                    else
                    {
                        @:Reschedule Appointment
                    }
                </button>
            </div>
        </div>

    </div>
</div>
<!-- //Modal -->

NazeeranHospitalManagement/Views/GetAppointment/_SearchOptions.cshtml
@model SearchScheduleViewModel

@if (!Model.IsFiltered)
{
    <div class="">
        @using (Html.BeginForm("GetSchedule", "GetAppointment", FormMethod.Get, new { @class = "form-inline" }))
        {
            <div class="input-group col-md-4">
                <span class="input-group-addon">Filter Results By</span>
                <select name="FilterOption" class="form-control" id="SearchOptions">
                    @foreach (SearchBy so in Enum.GetValues(typeof(SearchBy)))
                    {
                        if (Model.SearchOption != so)
                        {
                            <option value="@((int)so)">@so</option>
                        }
                    }
                </select>

            </div>

            <div class="input-group">
                @if (Model.SearchOption != SearchBy.Name)
                {
                    <div id="SearchOption_ByName" class="hidden">
                        <div class="input-group">
                            @Html.LabelFor(model => model.DoctorName, htmlAttributes: new { @class = "input-group-addon" })
                            @Html.EditorFor(model => model.DoctorName, new { htmlAttributes = new { @class = "form-control" } })
                            <div class="col-md-7">
                                @Html.ValidationMessageFor(model => model.DoctorName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                }

                @if (Model.SearchOption != SearchBy.Dates)
                {
                    <div id="SearchOption_ByDate" class="hidden">
                        <div class="input-group">
                            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "input-group-addon" })
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control date" } })
                            <div class="col-md-10">
                                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                }

                @if (Model.SearchOption != SearchBy.Department)
                {
                    <div id="SearchOption_ByDepartment" class="hidden">
                        <div class="input-group">
                            @Html.LabelFor(model => model.DepartmentName, htmlAttributes: new { @class = "input-group-addon" })
                            @Html.DropDownListFor(model => model.DepartmentId, Model.DepartmentList, htmlAttributes: new { @class = "form-control" })
                            <div class="col-md-10">
                                @Html.ValidationMessageFor(model => model.DepartmentId, "", htmlAttributes: new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                }
            </div>

            <div class="hidden">
                @Html.HiddenFor(model => model.SearchOption)
                @if (Model.SearchOption == SearchBy.Name)
                {
                    @Html.HiddenFor(model => model.DoctorName)
                }
                else if (Model.SearchOption == SearchBy.Department)
                {
                    @Html.HiddenFor(model => model.DepartmentId)
                }
                else if (Model.SearchOption == SearchBy.Dates)
                {
                    @Html.HiddenFor(model => model.Date)
                }

                else
                {
                    @Html.HiddenFor(model => model.DepartmentId)
                    @Html.HiddenFor(model => model.Date)
                    @Html.HiddenFor(model => model.DoctorName)
                }
            </div>

            <div class="form-group pull-right">
                <button type="submit" name="filterResults" class="btn btn-info">Filter</button>
            </div>
        }
    </div>
}